spring.application.name=bankProject
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# setx DB_URL "jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require"
# setx DB_USERNAME "postgres.fmrwjvpyiqmtirhbuzwn"
# setx DB_PASSWORD "fliqXC4gPoezctBt"

# spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
# spring.datasource.username=postgres.fmrwjvpyiqmtirhbuzwn
# spring.datasource.password=fliqXC4gPoezctBt

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true